// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxstcphzadnapawjkrrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4c3RjcGh6YWRuYXBhd2prcnJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDg0NjYsImV4cCI6MjA2MjI4NDQ2Nn0.TwJcpI26yqIXrtlJ55iC5IHXc-UBlDCpaERdx7KS8M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);